BATCH_SIZE = 64
TASK_NUM = 500
TASK_NUM_MAX = 500
SERVER_NUM = 5
TASK_NUM_OLD = TASK_NUM // SERVER_NUM

CPU_IDX = 0
RAM_IDX = 1
DISK_IDX = 2
PRIORITY_IDX = 3
RELEASE_TIME_IDX = 4
TIME_IDX = 5

RESOURCE_NUM = 3

TOTAL_DATA = 474443

REWARD_TARGET_IDX = 0
RESOURCE_TARGET_IDX = 1
TIME_TARGET_IDX = 2
PRIORITY_TARGET_IDX = 3
WAIT_TARGET_IDX = 4

TARGET_NUM = 5
TARGET_NAME = \
    ["Reward", "Reward1 - Resource Use", "Reward2 - Running Time", "Reward3 - Priority", "Reward3 - Waiting Time"]

MIN_TASK = 300
MAX_TASK = 500

MIN_SERVER = 5
MAX_SERVER = 15
